/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Update this file with
 *   `$ ./gradlew buildSrcVersions`
 */
object Libs {
    val splitties = Splitties

    object Splitties {
        const val android_base: String =
            "com.louiscad.splitties:splitties-fun-pack-android-base:3.0.0-alpha06"

        const val base_with_views_dsl: String =
            "com.louiscad.splitties:splitties-fun-pack-android-base-with-views-dsl:3.0.0-alpha06"
    }

    val room = Room

    object Room {
        const val room_runtime: String = "androidx.room:room-runtime:2.2.0-rc01"

        const val room_rxjava2: String = "androidx.room:room-rxjava2:2.2.0-rc01"
    }

    const val com_gradle_build_scan_gradle_plugin: String =
        "com.gradle.build-scan:com.gradle.build-scan.gradle.plugin:2.4.2"


    const val guava: String = "com.google.guava:guava:15.0"

    const val guice: String = "com.google.inject:guice:2.0"
}
